// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckgbnibsdlmyjaylmzjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrZ2JuaWJzZGxteWpheWxtempvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDAzOTksImV4cCI6MjA3NDQ3NjM5OX0.M9hihUaIzSvCYjoDDUVRg7cFhFzH6bvvrEdta7JvD9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
